[package]
name = "app-demo"
version.workspace = true
edition.workspace = true

[dependencies]
chimera-core = { path = "../../chimera-core" }
chimera-core-macros = { path = "../../chimera-core-macros" }
anyhow = { workspace = true}
inventory = "0.3"
tokio = { workspace = true }
